#!/usr/bin/env tsx
/**
 * [PATH]: scripts/pcs-gate.ts
 * PCS Gate 2.0 — computes Pattern Compliance Score for the current checkout.
 * Exit code 0 if PCS >= 0.997, otherwise WORLDHALT.
 *
 * DESIGN:
 * - Read-only gate: does not mutate source files.
 * - Uses existing artifacts (coverage/coverage-summary.json) when available.
 * - Appends a single line to tasks/PCS_SCORECARD.md if writable.
 */

import { existsSync, readFileSync, appendFileSync, readdirSync, statSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { resolve } from 'node:path';

const GATE = 0.997;
const START = 1.0;

const PENALTIES = {
  missingAgents: 0.080,
  missingMathcore: 0.050,
  todo: 0.070,
  coverageGlobalLow: 0.050,
  coverageCoreLow: 0.070,
  oidcMissing: 0.020,
  deprecatedDirty: 0.060,
  secretsLeak: 0.150,
} as const;

interface PCSFinding {
  rule: string;
  penalty: number;
  message: string;
}

interface PCSResult {
  pcs: number;
  status: 'PASS' | 'WORLDHALT';
  findings: PCSFinding[];
}

const SCORECARD_PATH = resolve('tasks/PCS_SCORECARD.md');

function penalize(
  findings: PCSFinding[],
  score: number,
  rule: string,
  penalty: number,
  message: string,
): { score: number; findings: PCSFinding[] } {
  findings.push({ rule, penalty, message });
  return { score: Math.round((score - penalty) * 10000) / 10000, findings };
}

function main(): void {
  const findings: PCSFinding[] = [];
  let state = { score: START, findings };

  // Required root anchors
  if (!existsSync(resolve('AGENTS.md'))) {
    state = penalize(state.findings, state.score, 'AGENTS.md', PENALTIES.missingAgents, 'Missing AGENTS.md');
  }
  if (!existsSync(resolve('01_governance/MATHCORE.md'))) {
    state = penalize(state.findings, state.score, 'MATHCORE', PENALTIES.missingMathcore, 'Missing 01_governance/MATHCORE.md');
  }
  if (!existsSync(resolve('02_protocols/OIDC_MIGRATION.md'))) {
    state = penalize(state.findings, state.score, 'OIDC_PLAN', PENALTIES.oidcMissing, 'Missing OIDC migration plan');
  }

  // Coverage gate (uses coverage-summary.json generated by vitest)
  const coveragePath = resolve('coverage/coverage-summary.json');
  if (existsSync(coveragePath)) {
    const summary = JSON.parse(readFileSync(coveragePath, 'utf-8')) as Record<string, { lines?: { pct?: number } }>;
    const globalPct = summary.total?.lines?.pct ?? 0;
    if (globalPct < 80) {
      state = penalize(state.findings, state.score, 'COVERAGE_GLOBAL', PENALTIES.coverageGlobalLow, `Global line coverage ${globalPct}% < 80%`);
    }
    const criticalPackages = [
      '@silence/contracts',
      '@silence/sdk',
      '@silence/events',
      '@silence/phi',
      '@silence/engine',
      '@silence/jitai',
    ];
    for (const pkg of criticalPackages) {
      const pct = summary[pkg]?.lines?.pct ?? 0;
      if (pct < 90) {
        state = penalize(state.findings, state.score, 'COVERAGE_CORE', PENALTIES.coverageCoreLow, `${pkg} line coverage ${pct}% < 90%`);
      }
    }
  } else {
    state = penalize(state.findings, state.score, 'COVERAGE_MISSING', PENALTIES.coverageGlobalLow, 'No coverage/coverage-summary.json found');
  }

  // Deprecated packages must not be referenced in production code
  const deprecatedPackages = [
    '@silence/behavioral-sequences',
    '@silence/database',
    '@silence/guards',
    '@silence/rhythmic-patterns',
  ];
  const deprecatedHits: string[] = [];
  const scanForDeprecated = (dir: string, exclude: string[]) => {
    for (const entry of readdirSync(dir)) {
      const full = resolve(dir, entry);
      if (['node_modules', 'dist', '.next', 'coverage'].includes(entry)) continue;
      if (exclude.some((e) => full.includes(e))) continue;
      const st = statSync(full);
      if (st.isDirectory()) {
        scanForDeprecated(full, exclude);
      } else if (st.isFile() && /\.(ts|tsx|js|json)$/.test(full)) {
        const content = readFileSync(full, 'utf-8');
        for (const pkg of deprecatedPackages) {
          const pattern = new RegExp(`(from|require\\()\\s*['\"]${pkg.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}['\"]`);
          if (pattern.test(content)) {
            deprecatedHits.push(`${full}: ${pkg}`);
            return;
          }
        }
      }
    }
  };
  const scanDirs = ['04_packages', '05_apps', '02_protocols', '06_infrastructure'];
  const staleDirs = scanDirs.filter((dir) => !existsSync(dir));
  if (staleDirs.length > 0) {
    console.error('WORLDHALT: stale PCS scan directories (paths do not exist):');
    for (const dir of staleDirs) {
      console.error(`  - ${dir}`);
    }
    process.exit(1);
  }

  scanForDeprecated('04_packages', deprecatedPackages.map((p) => `04_packages/@silence/${p.replace('@silence/', '')}`));
  scanForDeprecated('05_apps', []);
  scanForDeprecated('02_protocols', []);
  scanForDeprecated('06_infrastructure', []);
  if (deprecatedHits.length > 0) {
    state = penalize(state.findings, state.score, 'DEPRECATED_IMPORT', PENALTIES.deprecatedDirty, `Active import of deprecated package: ${deprecatedHits[0]}`);
  }

  // Secrets gate: ghp_ tokens forbidden in .git/config
  try {
    execSync('grep -r "ghp_" .git/config 2>/dev/null', { stdio: 'ignore' });
    state = penalize(state.findings, state.score, 'SECRETS_LEAK', PENALTIES.secretsLeak, 'ghp_ token detected in .git/config');
  } catch {
    // PASS
  }

  // Zero-fragment policy: no TODO/FIXME/XXX in active code
  try {
    const out = execSync(
      'grep -R --exclude-dir=node_modules --exclude-dir=dist --exclude-dir=.next --exclude-dir=coverage --exclude-dir=07_archive "TODO\\|FIXME\\|XXX" 04_packages 05_apps 02_protocols 06_infrastructure .github --include="*.ts" --include="*.tsx" --include="*.js" --include="*.yml" --include="*.yaml" --include="*.md" 2>/dev/null | head -5 || true',
      { encoding: 'utf-8' },
    );
    if (out.trim()) {
      const preview = out.trim().split('\n').slice(0, 3).join('; ');
      state = penalize(state.findings, state.score, 'TODO_MARKERS', PENALTIES.todo, `TODO/FIXME/XXX markers found: ${preview}`);
    }
  } catch {
    // ignore
  }

  const status = state.score >= GATE ? 'PASS' : 'WORLDHALT';
  const result: PCSResult = { pcs: state.score, status, findings: state.findings };

  console.log(JSON.stringify(result, null, 2));

  const sha = process.env.GITHUB_SHA ?? 'local';
  const scorecardLine = `- ${new Date().toISOString()} | PCS=${state.score} | STATUS=${status} | SHA=${sha} | FINDINGS=${state.findings.length}\n`;
  if (existsSync(SCORECARD_PATH)) {
    appendFileSync(SCORECARD_PATH, scorecardLine);
  }
  console.error(scorecardLine.trimEnd());

  if (status === 'WORLDHALT') {
    console.error(`WORLDHALT: PCS ${state.score} < ${GATE}`);
    process.exit(1);
  }
}

main();
