// src/lib/safety/keywords.ts
// Crisis detection keywords for PatternLens
// HARD = instant block, SOFT = Claude risk assessment

export const HARD_KEYWORDS_EN = [
  'kill myself',
  'killing myself',
  'want to die',
  'going to die',
  'suicide',
  'suicidal',
  'end my life',
  'end it all',
  'take my life',
  'hang myself',
  'shoot myself',
  'overdose',
  'slit my wrists',
  'jump off',
  'not want to live',
  'better off dead',
  'plan to die',
  'goodbye forever',
  'final goodbye',
  'no reason to live',
] as const;

export const HARD_KEYWORDS_PL = [
  'samobójstwo',
  'samobojstwo',
  'zabić się',
  'zabic sie',
  'chcę umrzeć',
  'chce umrzec',
  'skończyć z życiem',
  'skonczyc z zyciem',
  'odebrać sobie życie',
  'odebrac sobie zycie',
  'powiesić się',
  'powiesic sie',
  'podciąć żyły',
  'podciac zyly',
  'pociąć się',
  'pociac sie',
  'przedawkować',
  'przedawkowac',
  'skoczyć z mostu',
  'skoczyc z mostu',
  'nie chcę żyć',
  'nie chce zyc',
  'lepiej bym nie żył',
  'lepiej bym nie zyl',
  'pożegnanie na zawsze',
  'pozegnanie na zawsze',
] as const;

export const SOFT_KEYWORDS_EN = [
  'hopeless',
  'hopelessness',
  'worthless',
  'no hope',
  'no point',
  'pointless',
  'meaningless',
  'empty inside',
  'numb',
  'cant go on',
  'cannot go on',
  'giving up',
  'give up',
  'burden',
  'im a burden',
  'everyone hates me',
  'nobody cares',
  'no one cares',
  'alone',
  'so alone',
  'completely alone',
  'isolated',
  'trapped',
  'no way out',
  'cant escape',
  'darkness',
  'despair',
  'desperate',
  'suffering',
  'agony',
  'miserable',
  'hate myself',
  'hate my life',
  'self harm',
  'self-harm',
  'cutting',
  'hurt myself',
  'hurting myself',
  'punish myself',
  'dont deserve',
  'deserve to suffer',
  'want it to stop',
  'make it stop',
  'tired of living',
  'exhausted',
  'cant take it',
  'breaking point',
  'falling apart',
  'crisis',
  'emergency',
  'help me',
] as const;

export const SOFT_KEYWORDS_PL = [
  'beznadziejny',
  'beznadziejna',
  'beznadzieja',
  'bez nadziei',
  'bezwartościowy',
  'bezwartosciowy',
  'nic nie wart',
  'bez sensu',
  'bezsens',
  'bezcelowy',
  'pusty',
  'pusta',
  'pustka',
  'odrętwienie',
  'odretwienie',
  'nie dam rady',
  'poddaję się',
  'poddaje sie',
  'rezygnuję',
  'rezygnuje',
  'ciężar',
  'ciezar',
  'jestem ciężarem',
  'jestem ciezarem',
  'wszyscy mnie nienawidzą',
  'wszyscy mnie nienawidza',
  'nikt mnie nie kocha',
  'nikomu nie zależy',
  'nikomu nie zalezy',
  'samotny',
  'samotna',
  'samotność',
  'samotnosc',
  'zupełnie sam',
  'zupelnie sam',
  'odizolowany',
  'uwięziony',
  'uwieziony',
  'w pułapce',
  'w pulapce',
  'bez wyjścia',
  'bez wyjscia',
  'ciemność',
  'ciemnosc',
  'rozpacz',
  'zrozpaczony',
  'zdesperowany',
  'cierpienie',
  'męka',
  'meka',
  'nieszczęśliwy',
  'nieszczesliwy',
  'nienawidzę siebie',
  'nienawidze siebie',
  'nienawidzę swojego życia',
  'nienawidze swojego zycia',
  'samookaleczenie',
  'cięcie się',
  'ciecie sie',
  'skrzywdzić siebie',
  'skrzywdzic siebie',
  'ranić siebie',
  'ranic siebie',
  'karać siebie',
  'karac siebie',
  'nie zasługuję',
  'nie zasluguje',
  'chcę żeby to się skończyło',
  'chce zeby to sie skonczylo',
  'zmęczony życiem',
  'zmeczony zyciem',
  'wyczerpany',
  'nie wytrzymam',
  'punkt krytyczny',
  'rozpadam się',
  'rozpadam sie',
  'kryzys',
  'pomóż mi',
  'pomoz mi',
  'pomocy',
] as const;

export const ALL_HARD_KEYWORDS = [...HARD_KEYWORDS_EN, ...HARD_KEYWORDS_PL];
export const ALL_SOFT_KEYWORDS = [...SOFT_KEYWORDS_EN, ...SOFT_KEYWORDS_PL];

export type HardKeywordEN = typeof HARD_KEYWORDS_EN[number];
export type HardKeywordPL = typeof HARD_KEYWORDS_PL[number];
export type SoftKeywordEN = typeof SOFT_KEYWORDS_EN[number];
export type SoftKeywordPL = typeof SOFT_KEYWORDS_PL[number];
