"use client";

/**
 * components/ui/AIDisclosureBadge.tsx
 *
 * DIR-07: EU AI Act Art. 50 — AI Disclosure Badge
 *
 * Legal basis: EU AI Act (Regulation 2024/1689), Article 50(1)
 * "Providers of AI systems [...] shall ensure that natural persons
 * exposed to them know that they are interacting with an AI system."
 *
 * Compliance deadline: 2 August 2026
 * Classification: PatternLens = LIMITED RISK (see docs/eu-ai-act/risk-classification.md)
 *
 * S11 Language Standard: compliant
 * S11_SAFETY_GUARD — the list below enumerates prohibited terms for disclosure transparency only.
 * - Uses: pattern, structural, observation
 * - FORBIDDEN (not used): therapy, diagnosis, treatment, mental health,
 *   disorder, medical, medication, clinical, symptom, patient, illness, cure
 */

import React, { useState } from "react";
import { cn } from "@/constants/design-system";

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export type AIDisclosureBadgeVariant =
  | "inline"    // Small inline badge — use next to AI-generated content
  | "footer"    // Footer strip — use in page footer
  | "tooltip";  // Icon with expandable tooltip — compact, hover-reveal

export interface AIDisclosureBadgeProps {
  /**
   * Display variant.
   * @default "inline"
   */
  variant?: AIDisclosureBadgeVariant;

  /**
   * Whether to show the EU AI Act regulatory label.
   * Enabled by default — required for Art. 50 compliance.
   * @default true
   */
  showRegLabel?: boolean;

  /**
   * Additional CSS class names.
   */
  className?: string;

  /**
   * Override the disclosure text.
   * Default text is the Art. 50-compliant disclosure.
   */
  disclosureText?: string;

  /**
   * Whether to show the expandable detail panel (tooltip/inline variants).
   * @default true
   */
  expandable?: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// Icons (inline SVG — no external dependency)
// ─────────────────────────────────────────────────────────────────────────────

function SparkleIcon({ size = 14 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 16 16"
      fill="none"
      aria-hidden="true"
    >
      <path
        d="M8 1L9.5 6.5L15 8L9.5 9.5L8 15L6.5 9.5L1 8L6.5 6.5L8 1Z"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function ChevronDownIcon({ size = 12 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 12 12"
      fill="none"
      aria-hidden="true"
    >
      <path
        d="M2 4L6 8L10 4"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Default disclosure text (Art. 50 compliant)
// ─────────────────────────────────────────────────────────────────────────────

const DEFAULT_DISCLOSURE_TEXT =
  "This content was generated by an AI system. PatternLens uses AI to analyze structural behavioral patterns. Results are observations, not assessments of your personal state.";

const REG_LABEL = "EU AI Act · Art. 50";

// ─────────────────────────────────────────────────────────────────────────────
// Inline variant
// ─────────────────────────────────────────────────────────────────────────────

function InlineBadge({
  showRegLabel,
  disclosureText,
  expandable,
  className,
}: Required<Pick<AIDisclosureBadgeProps, "showRegLabel" | "disclosureText" | "expandable" | "className">>) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className={cn("flex flex-col gap-1", className)}>
      <div className="flex items-center gap-1.5">
        <span
          className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[11px] font-medium
                     bg-[rgba(74,144,226,0.12)] text-[#60a5fa] border border-[rgba(74,144,226,0.25)]
                     select-none"
          aria-label="AI-generated content — EU AI Act disclosure"
        >
          <SparkleIcon size={10} />
          AI
          {showRegLabel && (
            <span className="ml-1 text-[9px] opacity-60 font-normal hidden sm:inline">
              {REG_LABEL}
            </span>
          )}
        </span>

        {expandable && (
          <button
            type="button"
            onClick={() => setExpanded((v) => !v)}
            className="text-[11px] text-[#6e7681] hover:text-[#8b949e] flex items-center gap-0.5 transition-colors"
            aria-expanded={expanded}
            aria-controls="ai-disclosure-detail"
          >
            What is this?
            <span
              className={cn(
                "transition-transform duration-150",
                expanded ? "rotate-180" : "rotate-0"
              )}
            >
              <ChevronDownIcon />
            </span>
          </button>
        )}
      </div>

      {expandable && expanded && (
        <p
          id="ai-disclosure-detail"
          className="text-[11px] text-[#6e7681] leading-relaxed max-w-sm px-1"
          role="note"
        >
          {disclosureText}
        </p>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Footer variant
// ─────────────────────────────────────────────────────────────────────────────

function FooterBadge({
  showRegLabel,
  disclosureText,
  className,
}: Required<Pick<AIDisclosureBadgeProps, "showRegLabel" | "disclosureText" | "className">>) {
  return (
    <div
      className={cn(
        "flex items-center justify-center gap-2 py-2 px-4",
        "border-t border-[rgba(74,144,226,0.15)] bg-[rgba(74,144,226,0.04)]",
        className
      )}
      role="note"
      aria-label="AI disclosure — EU AI Act Art. 50"
    >
      <SparkleIcon size={12} />
      <span className="text-[11px] text-[#6e7681] leading-none">
        {disclosureText}
      </span>
      {showRegLabel && (
        <span className="text-[10px] text-[rgba(96,165,250,0.5)] hidden sm:inline shrink-0">
          {REG_LABEL}
        </span>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Tooltip variant
// ─────────────────────────────────────────────────────────────────────────────

function TooltipBadge({
  showRegLabel,
  disclosureText,
  className,
}: Required<Pick<AIDisclosureBadgeProps, "showRegLabel" | "disclosureText" | "className">>) {
  const [open, setOpen] = useState(false);

  return (
    <div className={cn("relative inline-block", className)}>
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        onBlur={() => setOpen(false)}
        className="inline-flex items-center justify-center w-5 h-5 rounded-full
                   bg-[rgba(74,144,226,0.12)] border border-[rgba(74,144,226,0.25)]
                   text-[#60a5fa] hover:bg-[rgba(74,144,226,0.2)] transition-colors"
        aria-label="AI-generated content — click for details"
        aria-expanded={open}
        aria-haspopup="true"
      >
        <SparkleIcon size={10} />
      </button>

      {open && (
        <div
          role="tooltip"
          className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 z-50
                     w-64 rounded-lg p-3 shadow-xl
                     bg-[#161b22] border border-[rgba(74,144,226,0.2)]
                     text-[11px] text-[#8b949e] leading-relaxed"
        >
          <div className="flex items-center gap-1.5 mb-1.5 text-[#60a5fa] font-medium">
            <SparkleIcon size={11} />
            AI-generated content
          </div>
          <p>{disclosureText}</p>
          {showRegLabel && (
            <p className="mt-1.5 text-[10px] text-[rgba(96,165,250,0.5)]">
              {REG_LABEL}
            </p>
          )}
          {/* Tooltip arrow */}
          <div className="absolute top-full left-1/2 -translate-x-1/2 -mt-px
                          border-4 border-transparent border-t-[#161b22]" />
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Main component
// ─────────────────────────────────────────────────────────────────────────────

/**
 * AIDisclosureBadge — EU AI Act Art. 50 compliance component.
 *
 * REQUIRED wherever AI-generated content is displayed to users.
 * Informs users they are interacting with an AI system, as mandated
 * by Article 50(1) of EU Regulation 2024/1689.
 *
 * @example
 * // Inline — next to AI-generated interpretation
 * <AIDisclosureBadge variant="inline" />
 *
 * @example
 * // Footer — in page footer
 * <AIDisclosureBadge variant="footer" />
 *
 * @example
 * // Tooltip — compact, hover/click to expand
 * <AIDisclosureBadge variant="tooltip" />
 */
export function AIDisclosureBadge({
  variant = "inline",
  showRegLabel = true,
  className = "",
  disclosureText = DEFAULT_DISCLOSURE_TEXT,
  expandable = true,
}: AIDisclosureBadgeProps) {
  if (variant === "footer") {
    return (
      <FooterBadge
        showRegLabel={showRegLabel}
        disclosureText={disclosureText}
        className={className}
      />
    );
  }

  if (variant === "tooltip") {
    return (
      <TooltipBadge
        showRegLabel={showRegLabel}
        disclosureText={disclosureText}
        className={className}
      />
    );
  }

  // Default: inline
  return (
    <InlineBadge
      showRegLabel={showRegLabel}
      disclosureText={disclosureText}
      expandable={expandable}
      className={className}
    />
  );
}

export default AIDisclosureBadge;
